### ISSUE TITLE
run !python StableDiffusionTelegram/bot.py have a error

### ISSUE THREAD

**Issue by Refarin** [jossalgon/StableDiffusionTelegram#3]
run the final part of the bot.py,it report 
`Fetching 16 files: 100% 16/16 [00:00<00:00, 25209.94it/s]
Fetching 16 files: 100% 16/16 [00:00<00:00, 28020.40it/s]
Traceback (most recent call last):
  File "StableDiffusionTelegram/bot.py", line 34, in <module>
    img2imgPipe = StableDiffusionImg2ImgPipeline.from_pretrained(MODEL_DATA, revision=revision, torch_dtype=torch_dtype, use_auth_token=USE_AUTH_TOKEN)
  File "/usr/local/lib/python3.7/dist-packages/diffusers/pipeline_utils.py", line 561, in from_pretrained
    model = pipeline_class(**init_kwargs)
  File "/content/StableDiffusionTelegram/image_to_image.py", line 36, in __init__
    scheduler = scheduler.set_format("pt")
AttributeError: 'PNDMScheduler' object has no attribute 'set_format'

i dont know how to deal with it. hope for your help.
`

**Comment by jossalgon** [comment]
Sorry for the delay, it's fixed now, it was a problem with the new version of diffusers, please do a "git pull" and "pip install -r requirements.txt --upgrade".
